name: db_infra
description: A command-line tool that help to automate your release workflow.
version: 0.0.2
homepage: https://github.com/db_infra


environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  archive: ">=3.3.0 <4.0.0"
  args: ">=2.3.0 <3.0.0"
  bdlogging: ">=0.0.2 <1.0.0"
  collection: ">=1.15.0 <2.0.0"
  encrypt: ">=5.0.1 <5.1.0"
  ftpconnect: ">=1.0.0 <1.1.0"
  gcloud: ">=0.8.6 <1.0.0"
  glob: '>=2.0.0 <3.0.0'
  googleapis_auth: ">=1.3.1 <2.0.0"
  http: '>=0.13.3 <0.14.0'
  io: ">=1.0.3 <2.0.0"
  jose: ">=0.3.2 <1.0.0"
  json_annotation: ">=4.5.0 <5.0.0"
  meta: '>=1.5.0 <2.0.0'
  path: '>=1.8.0 <2.0.0'

dev_dependencies:
  build_runner: any
  flutter_code_style: ^2.1.1
  json_serializable: ">=6.1.5 <7.0.0"
  test: ^1.17.12

executables:
  db_infra:
